spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ib-forum-database
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html