spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ib-forum-database
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp